// ─── STATE ───
const state = {
    player: {
        x: WORLD_W / 2, y: WORLD_H / 2, w: 16, h: 24,
        speed: 3, hp: 100, maxHp: 100,
        score: 0, gold: 0, kills: 0, wave: 1,
        dashing: false, dashCooldown: 0, dashTimer: 0,
        attacking: false, attackCooldown: 0, attackCount: 0,
        facingX: 0, facingY: 1,
        weapon: 'sword', ownedWeapons: ['sword'],
        weaponSlots: { 1: 'sword', 2: null, 3: null },
        upgrades: [], upgradeLevels: {},
        milestoneIndex: 0, nextEvolveKills: 170,
        animFrame: 0, animTimer: 0,
        phoenixUsed: false, cloneAttackTimer: 0,
        bossesKilled: 0, unlockedEnemyTypes: 1,
        unlockedDinoTypes: 2, unlockedSailorTypes: 2, unlockedAlienTypes: 2,
        streak: 0, streakTimer: 0, streakMult: 1,
        sizeScale: 1, damageMult: 1, orbAngle: 0,
        pet: null, petLevel: 0, chickenTimer: 0,
        petBranch: [0,0,0], petEvolveLevel: 0,
        petActionCount: 0, petActionThreshold: 0, petUpgradeReady: false,
        xp: 0, xpLevel: 0, xpToNext: 10, skillPoints: 0, skills: {},
        skillCritChance: 0, lifeStealBonus: 0, attackSpeedMult: 1,
        attackRangeBonus: 0, hasMomentum: false, momentumStacks: 0,
        goldMult: 1, furyKills: 0, secondChanceUsed: false,
        // Durability / blacksmith
        weaponDurability: { sword: 200 },
        weaponUpgrades: {},
        weaponWarnedLow: {},
        armor: { helmet: null, chest: null, leggings: null, boots: null },
        armorDurability: {},
        armorWarnedLow: {},
        fusionIngredients: {},
        maxWeaponSlots: 3,
        maxUpgrades: 6,
        totalGoldEarned: 0,
        character: 'knight',
        pineWood: 0, redWood: 0, bones: 0,
        torchTimer: 0,
        robotMalfunction: false, robotMalfunctionTimer: 0,
        cavemanEatSeq: '',
        branchCount: 0,
        humanKillsThisRun: 0,
        lakeSec1: 0, lakeSec2: 0,
        // Wizard-only fields
        mana: 0, maxMana: 100, manaRegen: 0.12, manaStacks: 1,
        runeSlots: { 1: null, 2: null, 3: null, 4: null },
        ownedRunes: {}, runeDurability: {},
    },
    camera: { x: 0, y: 0 },
    enemies: [], crocodiles: [], salamanders: [], fish: [], sharks: [], crabs: [], humanExplorers: [], alienExplorers: [], skeletonWarriors: [], trees: [], barricades: [], particles: [], projectiles: [], enemyProjectiles: [],
    butler: null, // Rich character's butler companion
    goldPickups: [], heartPickups: [], fireTrails: [], shockwaves: [], lightningEffects: [], damageNumbers: [],
    spiderWebs: [], treasureChests: [], eggs: [],
    bountyTarget: null,
    keys: {}, mouse: { x: 0, y: 0 }, mouseHeld: false,
    difficulty: null, diffMult: { enemyHpMult: 1, enemySpeedMult: 1, enemyDmgMult: 1, goldMult: 1 },
    gameOver: false, paused: true, shopOpen: false, blacksmithOpen: false, blacksmithTab: 'repair',
    upgradeOpen: false, evolveOpen: false, petEvolveOpen: false,
    pendingUpgradeChoices: [], shopWeapons: [],
    pendingUpgradeCount: 0, pendingEvolveCount: 0,
    frame: 0, notifTimer: 0, notifText: '',
    bossActive: false, bossWarningTimer: 0,
    waveTransition: false, waveTransTimer: 0,
    waveBreather: 0, shadowDemonActive: false, screenShakeDur: 0, screenShakeMag: 0,
    angelCooldown: 0, angelTimer: 0, postBossCooldown: 0,
    hordeWave: false, hordeTimer: 0,
    waveSpawnQueue: [], waveSpawnTimer: 0, waveAllSpawned: false,
    waveEnemiesTotal: 0, waveEnemiesKilled: 0,
    dayNight: { phase: 'day', timer: DAY_LEN, dayCount: 1, alpha: 0, eveningShown: false },
    skillTreeOpen: false,
    birdVortexes: [],
    pacifistTimer: 0,
    webbedTimer: 0,
    runAngelHeals: 0,
    runShadowDemonsKilled: 0,
    speedKillWindow: [],
    achievementsThisRun: [],
    characterSelectOpen: false,
    endlessMode: false,
    grimReaperSpawned: false,
    grimReaperDefeated: false,
    gamerShopStreak: 0, gamerShopOpen: false,
    waterFrames: 0,
    shopLocks: {}, shopLockedPrices: {},
    runStartTime: 0,
    wizardTrialActive: false,
    wizardTrialWaveTarget: 20,
    alienWorld: false,
    dinoWorld: false,
    underwater: false,
    sailorWorld: false,
    stickWorld: false,
    mapVariant: 'normal', // 'normal' | 'island' | 'canyon' | 'cave'
    // Mid-run events
    activeEvent: null,     // { id, name, desc, timer, duration, remove }
    _eclipseActive: false, _bloodMoonActive: false, _earthquakeActive: false,
    _meteorActive: false, _meteorTimer: 0, _healSpringActive: false, _healSpringTimer: 0,
    _frostActive: false,
    // Weather
    weather: { stage: 0, wavesLeft: 0, extreme: null, rainParticles: [], lightningFlash: 0, tornadoX: WORLD_W/2, tornadoY: WORLD_H/2, fogPatches: [] },
    telescopeActive: false,
    hasRubixCube: false,
    slipperyPatches: [],
    janitorPickupWindow: [],
    menuBg: null,
    joyDir: null,        // { x, y } — virtual joystick input (-1..1)
    gamepadDir: null,    // { x, y } — right-stick aim direction
    gamepadActive: false,
    mpMode: false,       // true after user confirms multiplayer
};
// Build pet overlay dynamically (will be called after DOM ready and after achievements grant pets)
// Deferred until after function definitions below.
